### ISSUE TITLE
Map controls off screen

### ISSUE THREAD

**Issue by nasanction** [VanillaPlusPlus/VanillaPlusPlus#3]
The control panel in the map is off-screen to the left and I am unable to use the options. Any help you can give would be greatly appreciated.
nasanction@yahoo.com

**Comment by Da0ne** [comment]
Hey! Thanks for reaching out! A hotfix update was just pushed to resolve that issue! Please update!

**Comment by nasanction** [comment]
Awesome, it's fixed! Thanks for your super fast response, and I love your mod!
